# Run tests against supported Node versions

version: 2.1

orbs:
  win: circleci/windows@5.0.0
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.4.3

executors:
  node20:
    docker:
      - image: cimg/node:20.0.0-browsers
    working_directory: ~/workspace
  node18:
    docker:
      - image: cimg/node:18.0.0-browsers
    working_directory: ~/workspace

jobs:
  test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - browser-tools/install-chrome
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Report core version
          command: echo 'console.log(require("jasmine-core").version())' | node
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .

  test_win:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: nvm install 18.0.0 && nvm use 18.0.0
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Report core version
          command: echo 'console.log(require("jasmine-core").version())' | node
      - run:
          name: Run tests
          command: npm test

  saucelabs_integration_test:
    executor: node18
    steps:
    - attach_workspace:
        at: .
    - browser-tools/install-chrome
    - run:
        name: Install Sauce Connect
        command: |
          cd /tmp
          curl https://saucelabs.com/downloads/sc-4.8.2-linux.tar.gz | tar zxf -
          chmod +x sc-4.8.2-linux/bin/sc
          mkdir -p ~/bin
          cp sc-4.8.2-linux/bin/sc ~/bin
          ~/bin/sc --version
    - run:
        name: Run tests
        command: |
          export PATH=$PATH:$HOME/workspace/bin
          export USE_SAUCE=true
          export SAUCE_TUNNEL_IDENTIFIER=$CIRCLE_WORKFLOW_JOB_ID
          scripts/start-sauce-connect sauce-pidfile
          set +o errexit
          npm test
          exitcode=$?
          set -o errexit
          scripts/stop-sauce-connect $(cat sauce-pidfile)
          exit $exitcode

workflows:
  version: 2
  push: &push_workflow
    jobs:
      - test:
          matrix:
            parameters:
                executor: ["node20", "node18"]
      - test_win
      - saucelabs_integration_test:
          requires:
            - "test-node18"
          filters:
            branches:
              ignore: /pull\/.*/ # Don't run on pull requests.

  cron:
    <<: *push_workflow
    triggers:
      - schedule:
          # Times are UTC.
          cron: "0 9 * * *"
          filters:
            branches:
               only:
                 - main
